version: '3.4'

services:
  microfrontend:
    image: ${DOCKER_REGISTRY-}microfrontend
    build:
      context: .
      dockerfile: MicroFrontEnd/Dockerfile

  microservices:
    image: ${DOCKER_REGISTRY-}microservices
    build:
      context: .
      dockerfile: MicroServices/Dockerfile


  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: OcelotAPIGw/Dockerfile

